import React, { useState } from 'react';
import { personalStoriesApi } from '../../services/api';
import { usePatient } from '../../context/PatientContext.jsx';

function scoreAnswer(userAnswer, keywords) {
  if (!userAnswer || !keywords || keywords.length === 0) return 0;
  const words = userAnswer.toLowerCase().split(/\s+/).map(w => w.replace(/[.,!?;:'"()]/g, ''));
  let matched = 0;
  keywords.forEach(kw => {
    const kwLower = kw.toLowerCase();
    if (words.some(w => w.includes(kwLower) || kwLower.includes(w))) {
      matched++;
    }
  });
  return Math.round((matched / keywords.length) * 100);
}

export default function StoryQuiz({ story, onComplete, onBack }) {
  const { patient } = usePatient();
  const [currentQ, setCurrentQ] = useState(0);
  const [answers, setAnswers] = useState([]);
  const [userInput, setUserInput] = useState('');
  const [submitted, setSubmitted] = useState(false);
  const [result, setResult] = useState(null);
  const [submitting, setSubmitting] = useState(false);
  const [reviewMode, setReviewMode] = useState(false);

  const questions = story.questions || [];
  const question = questions[currentQ];
  const isAutoGenerated = story._autoGenerated;

  const handleNext = () => {
    if (!userInput.trim()) return;
    const newAnswers = [...answers, { selectedAnswer: -1, textAnswer: userInput.trim() }];
    setAnswers(newAnswers);
    setUserInput('');

    if (currentQ < questions.length - 1) {
      setCurrentQ(prev => prev + 1);
    } else {
      submitQuiz(newAnswers);
    }
  };

  const submitQuiz = async (allAnswers) => {
    setSubmitting(true);

    // Score each answer using keywords
    let totalScore = 0;
    const scoredAnswers = allAnswers.map((ans, i) => {
      const q = questions[i];
      const accuracy = scoreAnswer(ans.textAnswer, q.keywords || []);
      totalScore += accuracy;
      return { ...ans, accuracy, isCorrect: accuracy >= 50 };
    });

    const avgAccuracy = Math.round(totalScore / questions.length);
    const scoreCount = scoredAnswers.filter(a => a.isCorrect).length;

    const localResult = {
      score: scoreCount,
      totalQuestions: questions.length,
      accuracy: avgAccuracy,
      answers: scoredAnswers.map((a, i) => ({
        question: questions[i].question,
        textAnswer: a.textAnswer,
        correctAnswer: questions[i].correctAnswer,
        accuracy: a.accuracy,
        isCorrect: a.isCorrect,
        keywords: questions[i].keywords || [],
      })),
    };

    if (isAutoGenerated) {
      try {
        const res = await personalStoriesApi.submitQuiz({
          storyId: story._id,
          patientId: patient?._id,
          answers: scoredAnswers.map(a => ({ selectedAnswer: -1, isCorrect: a.isCorrect })),
          score: scoreCount,
          totalQuestions: questions.length,
          accuracy: avgAccuracy,
          storyTitle: story.title || 'Story Quiz',
        });
        setResult({ ...localResult, ...res.data });
      } catch {
        setResult(localResult);
      }
    } else {
      try {
        const res = await personalStoriesApi.submitQuiz({
          storyId: story._id,
          patientId: patient?._id,
          answers: scoredAnswers.map(a => ({ selectedAnswer: -1, isCorrect: a.isCorrect })),
          storyTitle: story.title || 'Story Quiz',
        });
        setResult({ ...localResult, ...res.data });
      } catch {
        setResult(localResult);
      }
    }

    setSubmitted(true);
    setReviewMode(true);
    setSubmitting(false);
  };

  const handleBackToQuiz = () => {
    setReviewMode(false);
  };

  if (submitted && result) {
    return (
      <div style={{ maxWidth: '600px', margin: '0 auto', padding: '32px', background: '#fff', borderRadius: '16px', boxShadow: '0 2px 16px rgba(0,0,0,0.06)', border: '1px solid #e0ede0' }}>
        <div style={{ textAlign: 'center', marginBottom: '32px' }}>
          <span style={{ fontSize: '64px', display: 'block', marginBottom: '16px' }}>
            {result.accuracy >= 80 ? '🌟' : result.accuracy >= 50 ? '👍' : '💪'}
          </span>
          <h2 style={{ color: '#1a2e1a', marginBottom: '8px', fontSize: '24px' }}>Quiz Complete!</h2>
          <p style={{ color: '#666', marginBottom: '24px', fontSize: '16px' }}>
            You answered {result.score} out of {result.totalQuestions} questions well
          </p>

          <div style={{ display: 'flex', justifyContent: 'center', gap: '32px', marginBottom: '24px' }}>
            <div style={{ textAlign: 'center' }}>
              <div style={{ fontSize: '36px', fontWeight: 700, color: '#2d5a27' }}>{result.accuracy}%</div>
              <div style={{ fontSize: '13px', color: '#666' }}>Score</div>
            </div>
            <div style={{ textAlign: 'center' }}>
              <div style={{ fontSize: '36px', fontWeight: 700, color: '#2d5a27' }}>{result.score}/{result.totalQuestions}</div>
              <div style={{ fontSize: '13px', color: '#666' }}>Questions</div>
            </div>
          </div>
        </div>

        {/* Answer Review */}
        <div style={{ marginBottom: '24px' }}>
          <h3 style={{ fontSize: '16px', fontWeight: '700', color: '#1a2e1a', marginBottom: '16px' }}>Your Answers</h3>
          {result.answers?.map((ans, i) => (
            <div key={i} style={{ background: '#f8fdf8', borderRadius: '12px', padding: '16px', marginBottom: '12px', border: `2px solid ${ans.isCorrect ? '#86efac' : '#fca5a5'}` }}>
              <p style={{ fontSize: '14px', fontWeight: '600', color: '#1a2e1a', marginBottom: '8px' }}>{i + 1}. {ans.question}</p>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}>
                <span style={{ fontSize: '12px', fontWeight: '600', color: '#666' }}>Your answer:</span>
                <span style={{ fontSize: '13px', color: '#333', fontStyle: 'italic' }}>"{ans.textAnswer}"</span>
                <span style={{ fontSize: '12px', fontWeight: '700', color: ans.isCorrect ? '#16a34a' : '#dc2626', marginLeft: 'auto' }}>{ans.accuracy}%</span>
              </div>
              {ans.correctAnswer && (
                <div style={{ fontSize: '12px', color: '#888', marginTop: '4px' }}>
                  <span style={{ fontWeight: '600' }}>Model answer: </span>{ans.correctAnswer}
                </div>
              )}
            </div>
          ))}
        </div>

        <div style={{ display: 'flex', justifyContent: 'center' }}>
          <button onClick={onBack} style={{ padding: '12px 28px', borderRadius: '12px', background: 'linear-gradient(135deg, #3d7a3d, #2d5a2d)', color: '#fff', fontSize: '14px', fontWeight: '700', border: 'none', cursor: 'pointer' }}>Back to Stories</button>
        </div>
      </div>
    );
  }

  if (questions.length === 0) {
    return (
      <div style={{ maxWidth: '500px', margin: '0 auto', padding: '40px', background: '#fff', borderRadius: '16px', textAlign: 'center', boxShadow: '0 2px 16px rgba(0,0,0,0.06)', border: '1px solid #e0ede0' }}>
        <p style={{ fontSize: '48px', marginBottom: '16px' }}>📝</p>
        <h2 style={{ color: '#1a2e1a', marginBottom: '12px' }}>No Questions Available</h2>
        <p style={{ color: '#666', marginBottom: '24px' }}>There are no questions for this story yet.</p>
        <button onClick={onBack} style={{ padding: '12px 28px', borderRadius: '12px', background: 'linear-gradient(135deg, #3d7a3d, #2d5a2d)', color: '#fff', fontSize: '14px', fontWeight: '700', border: 'none', cursor: 'pointer' }}>Back to Stories</button>
      </div>
    );
  }

  return (
    <div style={{ maxWidth: '600px', margin: '0 auto', padding: '32px', background: '#fff', borderRadius: '16px', boxShadow: '0 2px 16px rgba(0,0,0,0.06)', border: '1px solid #e0ede0' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
        <button onClick={onBack} style={{ padding: '8px 16px', borderRadius: '8px', border: '1px solid #ddd', background: '#f5f5f5', color: '#333', fontSize: '13px', fontWeight: '600', cursor: 'pointer' }}>← Back</button>
        <span style={{ fontSize: '14px', color: '#666', fontWeight: 600 }}>Question {currentQ + 1} / {questions.length}</span>
      </div>

      <div style={{ display: 'flex', gap: '4px', marginBottom: '24px' }}>
        {questions.map((_, idx) => (
          <div key={idx} style={{ flex: 1, height: '6px', borderRadius: '3px', background: idx < currentQ ? '#2d5a27' : idx === currentQ ? '#5a9a5a' : '#e0ede0' }} />
        ))}
      </div>

      <h2 style={{ color: '#1a2e1a', marginBottom: '24px', fontSize: '18px', lineHeight: 1.5 }}>{question.question}</h2>

      <div style={{ marginBottom: '24px' }}>
        <textarea
          value={userInput}
          onChange={(e) => setUserInput(e.target.value)}
          placeholder="Type your answer here..."
          rows={4}
          style={{
            width: '100%', padding: '14px 18px', borderRadius: '12px',
            border: '2px solid #e0ede0', background: '#f8fdf8',
            fontSize: '15px', color: '#1a1a1a', lineHeight: 1.6,
            resize: 'vertical', fontFamily: 'inherit', outline: 'none',
            boxSizing: 'border-box',
          }}
          onFocus={(e) => { e.target.style.borderColor = '#3d7a3d'; }}
          onBlur={(e) => { e.target.style.borderColor = '#e0ede0'; }}
        />
        <p style={{ fontSize: '12px', color: '#999', marginTop: '6px' }}>Answer in your own words — we'll check for key details from the story.</p>
      </div>

      <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
        <button onClick={handleNext} disabled={!userInput.trim() || submitting} style={{
          padding: '12px 28px', borderRadius: '12px', border: 'none',
          background: !userInput.trim() ? '#ccc' : 'linear-gradient(135deg, #3d7a3d, #2d5a2d)',
          color: '#fff', fontSize: '14px', fontWeight: '700',
          cursor: !userInput.trim() ? 'not-allowed' : 'pointer',
        }}>
          {submitting ? 'Scoring...' : currentQ < questions.length - 1 ? 'Next →' : 'Finish'}
        </button>
      </div>
    </div>
  );
}
